### ISSUE TITLE
Modulo missing in translator.

### ISSUE THREAD

**Issue by MaximeJdDS** [ErykPiasecki07/VerbCalc#31]
Hello. :)

I would like to participate to your project, and to do that I would like to add the " modulo " in your translator. 
Furthermore, it's my first collaboration in open sourced project, so any advice is welcome. :)

I wish you all the best.

**Comment by ErykPiasecki07** [comment]
Hi! :)

New contributors are always welcome and modulo would be a very useful feature!
I see you have already forked the repo, so when you have something ready, feel free to open pull request!

If something does not work properly regarding the PR's opening process, let me know - this project is the first time I collaborate with broader open-source community instead of people I know personally, so if something with repository's permissions is wrong, or there are any other questions regarding the project, feel free to ask!

Thanks once more for your support!

**Comment by ErykPiasecki07** [comment]
Resolved by: #35
